# Generated by Django 2.2.10 on 2020-05-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_profile_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student',
            field=models.BooleanField(default=0),
        ),
    ]
