# Generated by Django 2.2.10 on 2020-05-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0008_auto_20200502_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='img_1',
        ),
        migrations.RemoveField(
            model_name='information',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='information',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='information',
            name='img_main',
        ),
        migrations.RemoveField(
            model_name='information',
            name='location',
        ),
        migrations.AddField(
            model_name='information',
            name='data',
            field=models.FileField(default=1, upload_to='practices/'),
            preserve_default=False,
        ),
    ]
