# Generated by Django 2.2.10 on 2020-05-02 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ICTapp', '0009_auto_20200502_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='img_main',
            field=models.ImageField(default=1, upload_to='practice_images'),
            preserve_default=False,
        ),
    ]
