# Generated by Django 2.2.10 on 2020-05-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
    ]
